# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MetaNativePoC' do
  pod 'AppCenter/Push', '~> 1.10.0'
  pod 'AppCenter/Crashes', '~> 1.10.0'
  pod 'AppCenter/Analytics', '~> 1.10.0'
  pod 'AppCenterReactNativeShared', '~> 1.9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MetaNativePoC

  

  platform :ios, '9.0'
  target 'MetaNativePoCTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MetaNativePoC-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MetaNativePoC-tvOS

  target 'MetaNativePoC-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
